/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.iub.views;

import co.edu.iub.interfaces.Prestable;
import co.edu.iub.models.Material;
import co.edu.iub.services.ServicioMaterial;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author jesus
 */
public class PrestarODevolverMaterialView extends javax.swing.JFrame {

    private final transient ServicioMaterial servicioMaterial;
    /**
     * Creates new form PrestarOCrearMaterialView
     */
    public PrestarODevolverMaterialView() {
        servicioMaterial = ServicioMaterial.getInstancia();
        initComponents();
        iniciarSelectMateriales();


    }

    private void iniciarSelectMateriales(){
        materialesSelect.removeAllItems();
        List<Material> materiales = servicioMaterial.obtenerMaterialesPrestables();
        materiales.forEach(material -> materialesSelect.addItem(material));
        materialesSelect.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prestarBtn = new javax.swing.JButton();
        devolverBtn = new javax.swing.JButton();
        descripcionTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        materialesSelect = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        stockTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        detallesTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        listarMaterialRedirect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prestarBtn.setText("Prestar");
        prestarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestarBtnActionPerformed(evt);
            }
        });

        devolverBtn.setText("Devolver");
        devolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverBtnActionPerformed(evt);
            }
        });

        descripcionTextField.setEditable(false);

        jLabel1.setText("Prestar o devolver material");

        materialesSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialesSelectActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripcion");

        stockTextField.setEditable(false);

        jLabel3.setText("Stock");

        detallesTextField.setEditable(false);

        jLabel4.setText("Detalles");

        listarMaterialRedirect.setText("Regresar");
        listarMaterialRedirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMaterialRedirectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(prestarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(devolverBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarMaterialRedirect)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(detallesTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcionTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(materialesSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(materialesSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detallesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prestarBtn)
                    .addComponent(devolverBtn)
                    .addComponent(listarMaterialRedirect))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materialesSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialesSelectActionPerformed

        Material material = (Material) materialesSelect.getSelectedItem();
		if(material == null){
            return;
        }

        descripcionTextField.setText(material.getDescripcion());
        stockTextField.setText(material.getStock().toString());
        detallesTextField.setText(material.mostrarDetalles());


    }//GEN-LAST:event_materialesSelectActionPerformed

    private void devolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverBtnActionPerformed
        Material material = (Material) materialesSelect.getSelectedItem();
        if(material == null){
            JOptionPane.showMessageDialog(null, "El material seleccionado es nulo");
            return;
        }

        if(material instanceof Prestable prestable){
            prestable.devolver();
            iniciarSelectMateriales();
            return;
        }

        JOptionPane.showMessageDialog(null, "El material seleccionado no aplica para prestamos o devoluciones");


    }//GEN-LAST:event_devolverBtnActionPerformed

    private void prestarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestarBtnActionPerformed
        Material material = (Material) materialesSelect.getSelectedItem();
        if(material == null){
            JOptionPane.showMessageDialog(null, "El material seleccionado es nulo");
            return;
        }

        if(material instanceof Prestable prestable){
            try {
                prestable.prestar();
                iniciarSelectMateriales();
                return;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                return;
            }
        }

        JOptionPane.showMessageDialog(null, "El material seleccionado no aplica para prestamos o devoluciones");

    }//GEN-LAST:event_prestarBtnActionPerformed

    private void listarMaterialRedirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMaterialRedirectActionPerformed
        ViewsHolder.listarMaterialView.cargarMateriales();
        ViewsHolder.cerrarYAbrirVista(this, ViewsHolder.listarMaterialView);
    }//GEN-LAST:event_listarMaterialRedirectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrestarODevolverMaterialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrestarODevolverMaterialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrestarODevolverMaterialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrestarODevolverMaterialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrestarODevolverMaterialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descripcionTextField;
    private javax.swing.JTextField detallesTextField;
    private javax.swing.JButton devolverBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton listarMaterialRedirect;
    private javax.swing.JComboBox<Material> materialesSelect;
    private javax.swing.JButton prestarBtn;
    private javax.swing.JTextField stockTextField;
    // End of variables declaration//GEN-END:variables
}
